### ISSUE TITLE
connection time out

### ISSUE THREAD

**Issue by jwangit** [Visa-Research/coproto#10]
Hi,

First all first, thank you for answering the questions people posted here. I really appreciate your help. 

I am emulating the socket communication between Alice and Bob using coproto on a single PC. This is a loopback communication. Alice and Bob are communicating in a server-client manner, where Alice is the server with IP address 127.0.0.1:1212.

There are 2 parties Alice, and Bob. 
Alice call a protocol as follows.
Proto A( ) {... ; std::vector<block> vectorA; ... MC_AWAIT(chl.recv(vectorA)); ...}

Bob call a protocol as follows.
Proto B( ) {...; std::vector<block> vectorB; ...  MC_AWAIT(chl.send(std::move(vecotrB)));...}

I am using **linux traffic control** to simulate the communication between Alice and Bob for different network bandwidth and delay.
When I was **not** using linux tc, the communication is OK. However, when I was using linux tc ( e.g., bandwidth to be 50MB, latency to be 20ms), I came across **connection timed out**. Then, I amended vectorB to be shorter (e.g., vectorB.size() = 32). There was no connection timed out error.

May I ask you if I want to transfer a large size of data, what should I do to overcome this connection time out?

Regards,
Jiabo

**Comment by ladnir** [comment]
Hmm, I would think this should work. Do you have a full example code?

**Comment by jwangit** [comment]
> Hmm, I would think this should work. Do you have a full example code?

Sure, I tried to follow the style of visa research's volepsi in my code. To ease problem description, I simply my code as follows.
`void bulkdata_transfer_Test()
{		
	std::string ip = "localhost:1212";
	int size = 100;
	int step = 1;
	std::vector<block> sent = generateItems(size, step);
	std::vector<block> tmp(sent);
	
	std::vector<block> recved(size);
	std::cout << "Bob: items generated." << std::endl;
/*  	for(int i ; i < size ; i++)
	{
		std::cout << "sent[" << i <<"]=" << sent[i] << ", ";
	}  */
	std::cout << std::endl;
    auto f0 = std::async([&]() { Alice(ip, recved); });
    auto f1 = std::async([&]() { Bob(ip, sent); });
    f0.get();
    f1.get();
	auto pass = checkTransfer(tmp,recved, size);
	if (!pass)
	{
		throw RTE_LOC;	/* code */
	}
	
}
`

**Comment by jwangit** [comment]
> Hmm, I would think this should work. Do you have a full example code?

Dear Professor,

After some investigation, I realized that the way I used linux tc is wrong. The burst is too small to buffer the data to send. It works if I make it larger. Sorry, for the inconvenience. 

Regards,
Jiabo

**Comment by ladnir** [comment]
Ah, no worries, glad you figured it out
