### ISSUE TITLE
how to provide their own networking layer which coproto will integrate with. 

### ISSUE THREAD

**Issue by yellow123Nike** [Visa-Research/coproto#2]
Hello, I want to add my networking layer in coproto, do I need to write it only in the customSocket() function? But I don't know how to write the customSocket() function, do you have an example please?t
![截屏2022-12-09 15 17 13](https://user-images.githubusercontent.com/37546857/206646594-c49cad01-2125-449d-831c-4ed52f6b8721.png)

**Comment by ladnir** [comment]
The simplest integration is with BufferingSocket.

This socket will hand you the messages to be sent. It's then up to you to send them. You can also set the incoming messages. There's an example in that file.

Or you can integrate your socket directly into the async api. That's a bit more complicated but it's explained there.

If your not sure, use BufferingSocket

**Comment by ladnir** [comment]
AsioSocket is an example. LocalAsyncSocket is another

**Comment by yellow123Nike** [comment]
OK, thank you！

**Comment by yellow123Nike** [comment]
Hello, I can add a sokcet to transfer the messages that need to be transferred in the BufferingSocket. Is this the correct understanding? Then, BufferingSocket only supports synchronous communication?

**Comment by ladnir** [comment]
`BufferingSocket` should never be modified. The idea of `BufferingSocket` is that it internally has two queues where outgoing and incoming messages are stored, respectively. 

When you provide an incoming message to a `BufferingSocket` via `socket.processInbound(...)`, it will first enqueue that message and then if someone calls (or has called) `socket.recv(...)`, that message will be removed from the queue and given to the `recv` caller. For `socket.send(...)`, the outgoing messages are simply queued in the `BufferingSocket`.

Concurrently to the execution of the protocol, i.e. some coroutine calling `send(...)` and `recv(...)`, you are expected to be querying `socket.getOutbound()` and `socket.processInbound(...)`. These calls are how you get the outbound and set the inbound messages. 

You could call `getOutbound(),processInbound(...)` from another thread but the simpler way is to eagerly start your existing `task<>` protocol object. This will start the protocol and run it until it can't proceed any further (eg needs to recv an incoming message). It will then  return and from then on you can continue executing the protocol until the task is done by calling `getOutbound(),processInbound(...)`.

```c++
#include "coproto/Socket/BufferingSocket.h"
#include "coproto/Common/Util.h"
void bufferingSocket()
{
    using namespace coproto;
    BufferingSocket sock;

    auto protocol = [&sock]() -> task<> {
        MC_BEGIN(task<>, &sock,
            buffer = std::vector<char>{});

        buffer.resize(42);
        MC_AWAIT(sock.send(buffer));
        MC_AWAIT(sock.recv(buffer));

        MC_AWAIT(sock.send(buffer));
        MC_AWAIT(sock.recv(buffer));
        MC_END();
    }();

    // start the protocol.
    auto eager = std::move(protocol) | macoro::make_eager();

    // the protocol ran until it hit the first recv. While it is not done, we need to perform
    // the IO operations manually by calling sock.getOutbound() and somehow forwarding 
    // those to the other party. In this example, we will actually give our own messages back 
    // to ourselves. However, in normal code you would actually send these messages to the 
    // other party using your own network layer.
    while (eager.is_ready() == false)
    {
        optional<std::vector<u8>> messages = sock.getOutbound();

        if (!messages)
        {
            // The socket was placed in a error state.
            throw COPROTO_RTE;
        }
        else
        {
            // somehow send *messages and receive the incoming messages.

            // in this example we will do something weird and
            // feed the protocols own messages back to itself.
            // This will run the protocol forward until it completes 
            // or needs more inbound messages
            sock.processInbound(*messages);
        }
    }
}
```

**Comment by yellow123Nike** [comment]
Perhaps I did not express myself very clearly. But thank you very much. I think I got it. buffersocket hands over the data that needs to be sent and received. So I can use this message to allow two participants who cannot communicate to complete the protocol.

**Comment by ladnir** [comment]
correct, it gives you a method to execute the protocol as a so-called round function. Each round produces a message to be sent to the other party. In this case a round is performed by calling `processInbound(...)` followed by `getOutbound()`.
