### ISSUE TITLE
Encounter difficulties when custom socket type.

### ISSUE THREAD

**Issue by jsuper** [Visa-Research/coproto#7]
Hi professor!

I want to custom the network layer to integrated with our exists service. the protocol is http2. 

I have write a custom socket and implement the await_suspend() to do real http call. But i found, the await_suspend() will call **3** times when i call socket.send(data) method, and the data is different every time. Real data is the last call of await_suspend() method.

How can I do check the data was real data which i want to send.

here is output log i added to debug
```text
Begin send data: helloworld
Call scheduler.send()....
Call await_ready...
Sending data:(), role is: send  
Call await resume now： coproto_error_code:0
Call await_ready...
Sending data:(
), role is: send     
Call await resume now： coproto_error_code:0
Call await_ready...
Sending data:(helloworld), role is: send 
Call await resume now： coproto_error_code:0
Send data finished
```
1. **fisrt round: data is emptry str**
2. **second round: data is linebreak char**
3. **third round, data is real data i want to send**

The send message code snippet as follow:
```cpp
	task<> sendByCustomSocket(coproto::Socket& sock, std::string message)
	{
		MC_BEGIN(task<>, message, &sock);
		std::cout << "Begin send data: "<< message << std::endl;
		// MC_AWAIT(sock.send(std::move(m))) ;
		MC_AWAIT(sock.send(message));

		std::cout<< Color::Blue << "Send data finished" << std::endl ;

		MC_END();
	}
```
await_susspend() method logic as follow.
```cpp
inline coroutine_handle<> CustomSocketType::Awatier::await_suspend(coroutine_handle<> h)
    {
        //do synchronous http call
        std::cout << "Sending data:(" << mData.data() << "), role is: " << (mType==Type::send ? "send" : "recv") << std::endl;
        mEc = code::success;

        return h;
    }
```

**Comment by RindalVisa** [comment]
are you still having issues? You can also use the BufferingSocket that can simplify inegration.
