### ISSUE TITLE
synchro/asynchro

### ISSUE THREAD

**Issue by jwangit** [Visa-Research/coproto#9]
Dear author,

Thanks for open accessing this great repo. I read it from the README that Coproto is developed in a sync manner (see below) but can be executed asynchronously across one or more threads. I am a fresh MPC developer and may I ask you a question on this issue?

Part of my code is as follows.

1	MC_BEGIN(Proto,this, &chl, &ch2, &recvSet, &payloadSet);
2       MC_AWAIT(ch2.send(recvSet.size())); 
3       MC_AWAIT(run(recvSet, chl, ch2));
4       MC_AWAIT(ch2.recv(mCardinality));   // recv cardinality frem server      
5       MC_END();

It compiles and works correctly. But I want to understand the sequence flow. May I know if line 2, 3, 4 run in a sequential manner on a single thread? Besides, in which file does Coproto provide example of async mode? I ask this question because I want to parallelize the tasks to the most to improve performance.

Thanks for your time!

**Comment by ladnir** [comment]
so for general info you should google c++ coroutines. coproto is follows the same model as the c++ standard coroutines but uses a different syntax. 

lines 2,3,4 will be run sequentially.

If you have two independent protocols, you can "fork" the socket `auto chl2 = chl.fork()`. You can then execute protocol 1 on `chl` and protocol 2 on `chl2`. The messages for each will be routed correctly even though there is only one underlying network socket. This is also referred to as multiplexing.

However, if you simply 
```cpp
MC_AWAIT(proto1(chl));
MC_AWAIT(proto2(chl2));
```
then these will still be executed sequentially. If you want them to run at the same time, you can
```cpp
MC_AWAIT(macoro::when_all_ready(proto1(chl),proto2(chl2)));
```

This will start both protocols. These protocols will start on the current thread. But at some point they will likely have to pause to wait on a network message that has not yet been received. When that message arrived, the thread that is processing networking messages will resume these protocol. However, you still wont get these running on multiple threads.

If you want to run on multiple threads, you can do this will an "executor", e.g. the `macoro::thread_pool`. You can give the `chl` a reference to this executor and all protocols that are resumed by the `chl` will be executed by the executor. see https://github.com/Visa-Research/coproto/blob/main/frontend/cpp14Tutorial.cpp#L799

**Comment by jwangit** [comment]
Thanks for your detailed reply.
